import turtle

alex = turtle.Turtle()
alex.pensize(5)
alex.penup()
wn=turtle.Screen()
wn.bgcolor("tan")

alex.goto(-360, 120)
alex.color("black")
alex.pencolor("yellow")

def Sand():
    Sky()
    drawAllSun()
    Cactus()
    Camels()

def square():
        alex.forward(710)
        alex.left(90)
        alex.forward(220)
        alex.left(90)
        alex.forward(710)
        alex.left(90)

def Sky():
    alex.fillcolor("#0000FF")
    alex.begin_fill()
    square()
    alex.end_fill()

def drawAllSun():#Akhilesh
    alex.goto(-280, 255)
    alex.dot(150)
    alex.penup()
    alex.goto(-280, 250)
    alex.pendown()
    alex.goto(-200, 140)
    alex.penup()
    alex.goto(-300, 230)
    alex.pendown()
    alex.goto(-320, 130)
    alex.penup()
    alex.goto(-210, 240)
    alex.pendown()
    alex.goto(-150, 240)
    alex.penup()
    alex.goto(-240,290)
    alex.pendown()
    alex.goto(-160,330)
    alex.penup()

def Cactus():
    alex.goto(-280,-290)
    alex.left(90)
    for i in range(4):
        alex.pencolor("green")
        alex.fillcolor("green")
        alex.begin_fill()
        Cacti()
        alex.end_fill()
        alex.pencolor("black")
        for i in range (4):
            alex.pendown()
            alex.right(90)
            alex.forward(5)
            alex.penup()
            alex.left(180)
            alex.forward(5)
            alex.right(90)
            alex.forward(30)
        alex.circle(30,180)
        alex.forward(10)
        for i in range (4):
            alex.pendown()
            alex.left(90)
            alex.forward(5)
            alex.penup()
            alex.right(180)
            alex.forward(5)
            alex.left(90)
            alex.forward(30)
        alex.left(180)
        alex.forward(10)
        alex.right(90)
        alex.forward(240)

def Cacti():
    alex.left(90)
    alex.pendown()
    alex.forward(100)
    alex.circle(30,180)
    alex.forward(100)
    alex.left(90)
    alex.forward(60)
    alex.penup()
    alex.left(90)

def Camels():
    alex.goto(-280,-150)
    alex.pencolor("black")
    for i in range (2):
        alex.left(90)
        alex.pendown()
        alex.forward(70)
        alex.left(45)
        alex.forward(60)
        alex.left(45)
        alex.forward(30)
        alex.right(90)
        alex.forward(20)
        alex.right(75)
        alex.forward(30)
        alex.penup()
        alex.right(90)
        alex.forward(10)
        alex.dot(10)
        alex.right(180)
        alex.forward(10)
        alex.right(90)
        alex.pendown()
        alex.forward(10)
        alex.left(70)
        alex.forward(15)
        alex.right(135)
        alex.forward(20)
        alex.left(45)
        alex.forward(20)
        alex.right(40)
        alex.forward(50)
        alex.left(75)
        alex.forward(60)
        alex.right(25)
        alex.forward(15)
        alex.right(35)
        alex.forward(130)
        alex.fillcolor("black")
        alex.begin_fill()
        alex.circle(5,-300)
        alex.end_fill()
        alex.right(200)
        alex.forward(20)
        alex.right(45)
        alex.forward(10)
        alex.left(105)
        alex.forward(80)
        alex.right(70)
        alex.forward(30)
        alex.right(110)
        alex.forward(75)
        alex.left(110)
        alex.forward(130)
        alex.left(90)
        alex.forward(70)
        alex.right(90)
        alex.forward(30)
        alex.right(180)
        alex.penup()
        alex.forward(300)
    
    
Sand()
wn.exitonclick
